export {default as NavbarComponent} from "./components/Navbar/NavbarComponent"
export {default as Footer} from "./components/Footer/Footer"
export {default as Home} from "./components/Home/Home"
export {default as Industries} from "./components/Industries/Industries"
export {default as Products} from "./components/Products/Products"
export {default as About} from "./components/About/About"
export {default as Contact} from "./components/Contact/Contact"
export {default as ProductCategory} from "./components/Products/ProductCategory"
export {default as ProductView} from "./components/Products/ProductView"
export {default as NewsFrom} from "./components/Footer/news-form/NewsForm"
export {default as ErrorPage} from "./components/Error/ErrorPage"
export {default as Blog} from "./components/Blog/Blog"
export {default as Blog1} from "./components/Blog/Pages/Blog1"

export {default as Login} from "./components/Admin/Login/Login"